### ISSUE TITLE
JAMM cannot locate bed or bedpe files even though they are present.

### ISSUE THREAD

**Issue by drashwinelkar** [mahmoudibrahim/JAMM#7]
Hello
I am using JAMM v1.0.7.6. I created the .bedpe files using bedtools -bedpe and my source bamfiles.
I want to use to call peaks in paired end mode. It does not recognise the -t parameter in the command line and keeps looking for .bed files when I have provided bedpe.
If I coerce the default to paired-end mode, it cannot locate the .bedpe in the sample folder provided. Is this a known issue or am I doing something wrong?
My commands are : 
for the paired-end:
~/sources/JAMM-JAMMv1.0.7.6/JAMM.sh -t 'paired'  -s JMJD3_bedpe -c JMJD3_sham_bedpe -g ~/sources/JAMM-JAMMv1.0.7.6/rn6.chrom.sizes -p 5 -T ./temp -o JMJD3_JAMM_peakmode

I just edited the JAMM.sh where the default is changed to paired and saved it as another copy with the same command as above. The error persists that it cannot find .bedpe or .bed files when the files are clearly present.

**Comment by mahmoudibrahim** [comment]
Hi

If I understand you correctly, you have files that end in ".bedpe" and JAMM is complaining about not finding them, correct?

JAMM can only recognize files that end in ".bed", -t paired tells JAMM that the ".bed" files are in bedpe format..meaning at least 6 columns chr, start, end, chr, start, end

hope that helps, let me know if I misunderstood this!

best wishes
Mahmoud

**Comment by drashwinelkar** [comment]
Yes I think what you said solved the issue. I was naming the bedpe files with the extension .bedpe and JAMM could not find the .bed files it needed! Thanks for the prompt reply.
